name: "Chromatic Deployment"

on: push

jobs:
  chromatic-deployment:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          exitZeroOnChanges: true
          autoAcceptChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Save PR number and Chromatic build outputs
        run: |
          mkdir -p ./pr
          echo "${{ github.event.pull_request.number }}" > ./pr/prNumber
          echo "${{ steps.chromatic.outputs.storybookUrl }}" > ./pr/storybookUrl
          echo "${{ steps.chromatic.outputs.buildUrl }}" > ./pr/buildUrl
