name: "E2E Test"

on:
  pull_request:
    branches:
      - develop

#  - name: Waiting for 200 from the Vercel Preview
#         uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
#         id: waitForDeploy
#         with:
#           token: ${{ secrets.TOKEN }}
#           max_timeout: 300

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.17.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Install playwright
        run: yarn playwright install --with-deps

      - name: Run playwright tests
        run: yarn e2e:ui
        # env:
        #   BASE_URL: ${{ steps.waitForDeploy.outputs.url }}
        # env:
        # PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
